version: "3.7"

x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/user1/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user1/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.gitconfig:/home/user1/.gitconfig"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined


services:

# Images
  ros2-control-sim-apt-iron-ubuntu-dev-image:
    image: elandini84/ros2-bench-test:ros2Ctrl_sim_apt_ubuntu22.04_iron_devel
    build:
      context: .
      dockerfile: Dockerfile
      target: ros2_ctrl_apt
      args:
        - base_img=elandini84/r1images:tourSim2_ubuntu22.04_iron_devel
        - ros2_distro=iron

  ros2-control-sim-apt-iron-ubuntu-dev-container:
    image: elandini84/ros2-bench-test:ros2Ctrl_sim_apt_ubuntu22.04_iron_devel
    <<: *base
    container_name: ros2-control-sim-apt-iron-ubuntu-dev-container
    command: terminator -g /home/user1/.config/terminator/config