version: "3.7"

x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.gitconfig:/home/yarp-user/.gitconfig"
    - "${ROBOT_CODE}/yarp-devices-google-cloud:/home/yarp-user/robotology/yarp-devices-google-cloud:rw"
    - "${ROBOT_CODE}/yarp:/home/yarp-user/robotology/yarp:rw"
    - "${ROBOT_CODE}/yarp/build_docker:/home/yarp-user/robotology/yarp/build:rw"
    - "${SECRETS_DATA}/HSP-Speech-Interaction-DEV/hsp-speech-test/hsp-speech-interaction-dev-ad51a35ee0ea.json:/home/yarp-user/.config/google-credential/hsp_google.json"
    - "${HOME}/userDump/robotinterface:/home/yarp-user/robotinterface:rw"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined
x-general: &general
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/credentials/google-credentials/hsp_google.json:/home/user/.config/google-credential/hsp_google.json"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined
x-nlp: &nlp
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/credentials/google-credentials/hsp_google.json:/home/user/.config/google-credential/hsp_google.json"
    - "${HOME}/.config/credentials/azure-credentials/config.env:/home/user/.env/config.env"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined

services:

# Images
  gccpp-master-ubuntu-v2-22:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          google_cloud_version: v2.22.x
          user_name: yarp-user
  gccpp-master-cuda-v2-22:
    image: elandini84/google_cloud_cpp:v2.22_yarp_cuda.11.7.1-cudnn8_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:cuda.11.7.1-cudnn8_master
          google_cloud_version: v2.22.x
          user_name: yarp-user
  nlp-tools-v2-22-aux:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_aux
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/llm_gpt:aux
          google_cloud_version: v2.22.x
          user_name: user

# Containers
  gccpp-master-ubuntu-v2-22-container:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-22-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  gccpp-master-cuda-v2-22-container:
    image: elandini84/google_cloud_cpp:v2.22_yarp_cuda.11.7.1-cudnn8_master
    <<: *base
    container_name: gccpp-master-cuda-v2-22-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  gccpp-master-ubuntu-v2-22-valgrind:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-22-valgrind-container
    command: bash -c "sudo apt install -y valgrind ninja-build && terminator -g /home/yarp-user/.config/terminator/config"
  gccpp-master-ubuntu-v2-22-general-container:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    <<: *general
    container_name: gccpp-master-ubuntu-v2-22-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  nlp-tools-v2-22-aux-container:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_aux
    <<: *nlp
    container_name: nlp-tools-v2-22-aux-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  nlp-tools-v2-22-aux-yarprun:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_aux
    <<: *nlp
    container_name: nlp-tools-v2-22-aux-container
    command: bash -c "yarp conf 192.168.100.10 10000 && yarprun --server /console-llm --log"