version: "3.7"

x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.gitconfig:/home/yarp-user/.gitconfig"
    - "${ROBOT_CODE}/yarp-devices-google-cloud:/home/yarp-user/robotology/yarp-devices-google-cloud:rw"
    - "${ROBOT_CODE}/yarp:/home/yarp-user/robotology/yarp:rw"
    - "${ROBOT_CODE}/yarp/build_docker:/home/yarp-user/robotology/yarp/build:rw"
    - "${SECRETS_DATA}/HSP-Speech-Interaction-DEV/hsp-speech-test/hsp-speech-interaction-dev-ad51a35ee0ea.json:/home/yarp-user/.config/google-credential/hsp_google.json"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined

services:

# Images
  gccpp-master-ubuntu-v2-12:
    image: elandini84/google_cloud_cpp:v2.12_yarp_ubuntu_22_04_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          google_cloud_version: v2.12.x
  gccpp-master-ubuntu-v2-20:
    image: elandini84/google_cloud_cpp:v2.20_yarp_ubuntu_22_04_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          google_cloud_version: v2.20.x
  gccpp-master-cuda-v2-20:
    image: elandini84/google_cloud_cpp:v2.20_yarp_cuda.11.7.1-cudnn8_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:cuda.11.7.1-cudnn8_master
          google_cloud_version: v2.20.x

# Containers
  gccpp-master-ubuntu-v2-12-container:
    image: elandini84/google_cloud_cpp:v2.12_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-12-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  gccpp-master-ubuntu-v2-20-container:
    image: elandini84/google_cloud_cpp:v2.20_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-20-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  gccpp-master-ubuntu-v2-12-valgrind:
    image: elandini84/google_cloud_cpp:v2.12_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-12-container
    command: bash -c "sudo apt install -y valgrind ninja-build && terminator -g /home/yarp-user/.config/terminator/config"
