version: "3.7"

x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.gitconfig:/home/yarp-user/.gitconfig"
    - "${ROBOT_CODE}/yarp-devices-google-cloud:/home/yarp-user/robotology/yarp-devices-google-cloud:rw"
    - "${ROBOT_CODE}/yarp:/home/yarp-user/robotology/yarp:rw"
    - "${ROBOT_CODE}/yarp/build_docker:/home/yarp-user/robotology/yarp/build:rw"
    - "${SECRETS_DATA}/HSP-Speech-Interaction-DEV/hsp-speech-test/hsp-speech-interaction-dev-ad51a35ee0ea.json:/home/yarp-user/.config/google-credential/hsp_google.json"
    - "${HOME}/userDump/robotinterface:/home/yarp-user/robotinterface:rw"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined
x-general: &general
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/credentials/google-credentials/hsp_google.json:/home/yarp-user/.config/google-credential/hsp_google.json"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined

services:

# Images
  gccp-master-ubuntu-vcpkg-2-28:
    image: elandini84/google_cloud_cpp:vcpkg2.28_yarp_ubuntu_22_04_master
    build:
      context: .
      dockerfile: Dockerfile_vcpkg
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          robot_code: /usr/local/src/robot
          google_cloud_version: a89dc1d0762103c132decd4eb57e8c014b01455f
          user_name: yarp-user
  gccp-master-cuda-vcpkg-2-28:
    image: elandini84/google_cloud_cpp:vcpkg2.28_yarp_cuda.11.7.1-cudnn8_master
    build:
      context: .
      dockerfile: Dockerfile_vcpkg
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          robot_code: /usr/local/src/robot
          google_cloud_version: a89dc1d0762103c132decd4eb57e8c014b01455f
          user_name: yarp-user
  gccpp-master-ubuntu-v2-22:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          robot_code: /usr/local/src/robot
          grcp_version: v1.60.0
          google_cloud_version: v2.22.0
          open_telemetry_version: v1.13.0
          nlohmann_json_version: v3.11.3
          crc32c_version: 1.1.2
          user_name: yarp-user
          jval: 8
  gccpp-master-cuda-v2-22:
    image: elandini84/google_cloud_cpp:v2.22_yarp_cuda.11.7.1-cudnn8_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:cuda.11.7.1-cudnn8_master
          robot_code: /usr/local/src/robot
          grcp_version: v1.60.0
          google_cloud_version: v2.22.0
          open_telemetry_version: v1.13.0
          nlohmann_json_version: v3.11.3
          crc32c_version: 1.1.2
          user_name: yarp-user
          jval: 8
  gccpp-slow-master-ubuntu-v2-22:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:ubuntu_22_04_master
          robot_code: /usr/local/src/robot
          grcp_version: v1.60.0
          google_cloud_version: v2.22.0
          open_telemetry_version: v1.13.0
          nlohmann_json_version: v3.11.3
          crc32c_version: 1.1.2
          user_name: yarp-user
          jval: 4
  gccpp-slow-master-cuda-v2-22:
    image: elandini84/google_cloud_cpp:v2.22_yarp_cuda.11.7.1-cudnn8_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/yarp:cuda.11.7.1-cudnn8_master
          robot_code: /usr/local/src/robot
          google_cloud_version: v2.22.0
          user_name: yarp-user
          jval: 4

# Containers
  gccpp-master-ubuntu-v2-22-container:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-22-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  gccpp-master-cuda-v2-22-container:
    image: elandini84/google_cloud_cpp:v2.22_yarp_cuda.11.7.1-cudnn8_master
    <<: *base
    container_name: gccpp-master-cuda-v2-22-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  gccpp-master-ubuntu-v2-22-valgrind:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    <<: *base
    container_name: gccpp-master-ubuntu-v2-22-valgrind-container
    command: bash -c "sudo apt install -y valgrind ninja-build && terminator -g /home/yarp-user/.config/terminator/config"
  gccpp-master-ubuntu-v2-22-general-container:
    image: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
    <<: *general
    container_name: gccpp-master-ubuntu-v2-22-container
    command: terminator -g /home/yarp-user/.config/terminator/config
