version: "3.7"
services:
# Image
  landocker:
    image: landocker/win10
    build:
      context: .
      network: host
      dockerfile: Dockerfile
  nav-ros-core:
    image: landocker/win10
    container_name: nav-ros-core
    environment:
    - YARP_COLORED_OUTPUT=1
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_FORWARD_CODEINFO_ENABLE=1
    - ROS_MASTER_URI=http://localhost:11311
    - ROS_DISTRO=noetic
    command: bash -c "source /opt/ros/noetic/setup.bash && roscore"
    network_mode: host
    ipc: host
  nav-ros-server:
    image: landocker/win10
    container_name: nav-ros-server
    environment:
    - YARP_COLORED_OUTPUT=1
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_FORWARD_CODEINFO_ENABLE=1
    - ROS_MASTER_URI=http://localhost:11311
    - ROS_DISTRO=noetic
    command: sh -c "yarp server --ros"
    network_mode: host
    ipc: host
    depends_on:
      - nav-ros-core
  nav-ros-host:
    image: landocker/win10
    container_name: nav-ros-host
    environment:
    - DISPLAY=host.docker.internal:0
    - YARP_COLORED_OUTPUT=1
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_FORWARD_CODEINFO_ENABLE=1
    - ROS_MASTER_URI=http://localhost:11311
    - ROS_DISTRO=noetic
    - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}/:/home/user1/.Xauthority:rw"
      - "/home/elandini/mainDump:/home/user1/ex_data_mount"
      - "/home/elandini/mainScript:/home/user1/ex_stuff"
      - "/home/elandini/mainSrc:/home/user1/mntCode"
    command: sh -c "yarp detect --write && yarp run --server /console --log"
    network_mode: host
    ipc: host
    depends_on:
      - nav-ros-server
