version: "3.7"

x-nlp: &nlp
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/yarp-user/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/yarp-user/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "${HOME}/.config/yarp:/home/yarp-user/.config/yarp"
    - "${HOME}/.config/credentials/google-credentials/hsp_google.json:/home/yarp-user/.config/google-credential/hsp_google.json"
    - "${HOME}/.config/credentials/azure-credentials/config.env:/home/yarp-user/.env/config.env"
  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined

services:

# Images
  nlp-tools-v2-22-aux:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_aux
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
          tour_branch: iron
          llm_branch: feat/aux_module
          robot_code: /usr/local/src/robot
          user_name: yarp-user
  nlp-tools-v2-22-master:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_master
    build:
      context: .
      dockerfile: Dockerfile
      args:
          base_img: elandini84/google_cloud_cpp:v2.22_yarp_ubuntu_22_04_master
          tour_branch: iron
          llm_branch: master
          robot_code: /usr/local/src/robot
          user_name: yarp-user

# Containers
  nlp-tools-v2-22-aux-container:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_aux
    <<: *nlp
    container_name: nlp-tools-v2-22-aux-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  nlp-tools-v2-22-aux-yarprun:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_aux
    <<: *nlp
    container_name: nlp-tools-v2-22-aux-container
    command: bash -c "yarp conf 192.168.100.10 10000 && yarprun --server /console-llm --log"
  nlp-tools-v2-22-master-container:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_master
    <<: *nlp
    container_name: nlp-tools-v2-22-master-container
    command: terminator -g /home/yarp-user/.config/terminator/config
  nlp-tools-v2-22-master-yarprun:
    image: elandini84/nlp_tools:gccpp_v2.22_llm_master
    <<: *nlp
    container_name: nlp-tools-v2-22-master-container
    command: bash -c "yarp conf 192.168.100.10 10000 && yarprun --server /console-llm --log"